name: Build

on:
  push:
    branches:
      - main
      - 'release/*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Build with make
        run: |
          make clean
          make

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: RDM-macos-build
          path: ./RDM.app
